### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by jlyon** [proudcity/pattern#29]
- [x] Share inline, with Label
- [x] Add font size 
- [x] Rm connect 
- [x] Rm share from sidebar
- [x] white bg

**Comment by jlyon** [comment]
@aschmoe @lukefretwell done. Thoughts?

**Comment by lukefretwell** [comment]
This one? 

http://pattern.getproudcity.com/#sg-footer

**Comment by jlyon** [comment]
Sorry, meant to include the link: http://pattern.getproudcity.com/?v=&page=01-page

**Comment by lukefretwell** [comment]
Thank you.

Can we do a more unified look that simplifies the font colors?

See: https://www.zendesk.com/

Comments:
- font/link color all the same
- if a city puts in a logo, is it going to be the same one as in the header? If so, can we do this to it in the footer? http://thenewcode.com/532/Convert-Images-To-Black-And-White-With-CSS
- feels like there needs to be more top/bottom padding
- headers, link text could be smaller
- Translate/size look like an after-thought. I like what Google does with translate on /analytics (http://www.google.com/analytics/) and has it in the footer but separated from the main footer content. In our case, I'd put it where they have 'Follow us ...' and separate with a line. That way it's more accessible and universal.

Not sure share/accessibility band applies to footer comments, but adding just in case:
- would make all the same font size
- might be cleaner to put a colon after 'Share' and make the social media links grey (similar to White House), so that they are a little more separated from the main content and stand out a little more
-

**Comment by jlyon** [comment]
- [x] Action bar = gray
- [x] Footer = white
- [x] Action bar: put things together
- [x] Text color: grayify
- [x] Put share/translate together, buttonify @lukefretwell will do more

**Comment by jlyon** [comment]
Took care of these items. Increased the padding slightly. Made each item into it's own link similar to tn.gov. Thoughts @aschmoe @lukefretwell?

http://pattern.getproudcity.com/?v=&page=01-page

**Comment by lukefretwell** [comment]
@jlyon I'm still seeing old view.

**Comment by jlyon** [comment]
@lukefretwell sry refresh

**Comment by lukefretwell** [comment]
Comments:
- Make headings h5 or equivalent size.
- Make text 14 px.
- Make link/text lighter (like #999).
- 'Proudly serving ...' text and icon could be smaller. 'Proudly serving' text looks clunky. Maybe bold? Think the styling here (hero and footer) are perfect: slc.helmcivic.com
- I like the action band. Might be good to make the text color a gray. The translate functionality doesn't work for me. When I click on it, it goes away.

**Comment by jlyon** [comment]
Updated: http://pattern.getproudcity.com/?v=&page=01-page

**Comment by aschmoe** [comment]
Think this is looking really sharp.

**Comment by lukefretwell** [comment]
+1

Only thing I see is that think needs some more top/bottom padding in the white section.
